name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch: 
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write  # This line gives the "Write" permission directly
    runs-on: ubuntu-latest
    steps:
      - name: generate-pacman-graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ishitasingh16
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?palette=github-dark
          
      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
